### PR TITLE
changes to be able to use streaming with seaside

### PR DESCRIPTION
**Pull request by pdebruic**
This is part of https://github.com/SeasideSt/Seaside/pull/1319

### CODE REVIEW

**Comment by dalehenrich** [comment]
@pdebruic could you make a simple change on your branch so that you can  trigger the github action for this pull request? Stupid github actions get disabled and I don't know how to force a formerly disabled action to be run against a pull request ... I'm guessing that now that I have re-enabled the action it should run if you make an additional change...

**Comment by dalehenrich** [comment]
@pdebruic, we're getting some test failures and it isn't obvious from looking at the stacks whether these failures are due to your recent changes, or changes that have been made to other parts of the infrastructure in the last two months (since the actions were disabled) ... if it turns out that you're changes aren't the root cause, I'll take a look at things and see what's up ...

**Comment by pdebruic** [comment]
I'm sure its mine.  I forgot normal zinc doesn't have Grease loaded.  So I'll fix it when I can soon!

**Comment by pdebruic** [comment]
OK I fixed it.  I think that last failure is one you've gotta look at.

**Comment by dalehenrich** [comment]
Yea, that one is a web-hook that sends results to a slack channel ... but it needs a secret key ... so there are more secrets about github actions that I will have to learn :) ... Thanks!

**Pull request merged**
