### PR TITLE
Issue #83 (ZnUnknownHttpMethod errors)

### PR DESCRIPTION
**Pull request by dassi**
Issue #83 on GemStone, fix for repeatedly creating a ZnUnknownHttpMethod error on every single request.

### CODE REVIEW

**Comment by dassi** [comment]
Solution taken from here: https://github.com/GsDevKit/GsDevKit_home/issues/169#issuecomment-418545793

**Comment by dalehenrich** [comment]
@dassi, the fix looks good, but It seems that the github actions weren't triggered for this PR ... so unless this is a problem for you, I plan to fiddle around with the github actions to see if I can trigger a run before doing the merge ...

Much appreciated by the way!

**Comment by dalehenrich** [comment]
... it looks like I was able to get [PR actions to run](https://github.com/GsDevKit/zinc/actions/runs/1239238360)

**Comment by dalehenrich** [comment]
... well the action ran but only on gsmaster and not for this PR ... also a bunch of failures on master branch in web socket tests ...  I don't have the cycles to fully focus on resollving the gs_master  issue, but I'll try to squeeze in some time over the next day or two to get things back in shape ...

**Comment by dassi** [comment]
@dalehenrich github actions are new to me, some sort to trigger CI tests, I guess. I'm happy to contribute tiny bits, happy if they make it to the main branch sometime. Not in a hurry, since my app now runs on my branch. Thanks!  :-)

**Comment by dalehenrich** [comment]
@dassi good to know ... github ci is like travis-ci, but travis-ci has shut down for open source projects ... the tiny bits are the important bits so your contributions are much appreciated ...

**Pull request merged**
